### ISSUE TITLE
Installation Fail

### ISSUE THREAD

**Issue by lmy06** [ICGC-TCGA-PanCancer/PCAP-core#152]
Hi,
I am getting this error while installing PCAP-core on Linux(perl  v5.10.1),

$./setup.sh /home/lmy/tools/PCAP-core-2.1.3/
Max compilation CPUs set to 6
App::cpanminus is up to date. (1.7043)
/home/lmy/tools/PCAP-core-2.1.3/bin/cpanm
File::ShareDir is up to date. (1.104)
File::ShareDir::Install is up to date. (0.11)
Const::Fast is up to date. (0.014)
Building jkentUtils ...
Building htslib ... previously installed ...
Building bam_stats ... previously installed ...
Building BWA ... previously installed ...
Building biobambam ... previously installed ...
Building samtools ... previously installed ...
Building Bio::DB::HTS ...Module::Build is up to date. (0.4224)
Bio::Root::Version is up to date. (1.007002)
/home/lmy/tools/source/PCAP-core-2.1.3/install_tmp
lzma.h library header not found in /usr/include. Please install it and try again.
On Debian/Ubuntu systems you can do this with the command:

  apt-get install liblzma-dev

I tried, and I cant install the liblzma-dev.deb file in Linux, and I don't have toot permission to write under /usr/include 

What Should I do now?

**Comment by keiranmraine** [comment]
If you don't have root permissions on the system you will have to discuss with your administrators.

This repository is now legacy code and new development is on [cancerit/PCAP-core](https://github.com/cancerit/PCAP-core).  That version also links to a [docker version](https://github.com/cancerit/dockstore-cgpmap) (mapping only) which can also be executed under the Dockstore.org framework.

If you are looking for the full analysis stack you can use [dockstore-cgpwgs](https://github.com/cancerit/dockstore-cgpwgs) which includes full WGS analysis.
