### ISSUE TITLE
PCAP-core tests

### ISSUE THREAD

**Issue by ink1** [ICGC-TCGA-PanCancer/PCAP-core#75]
The following errors were encountered while running "make test"
```bash
t/3_external_progs.t .. 
...
    not ok 1 - Expect version 0.0.189 for bamcollate2
    not ok 2 - Expect version 0.0.189 for bammarkduplicates
    not ok 3 - Expect version 0.0.189 for bamsort
```
I think this is simply because LD_LIBRARY_PATH is not updated and libmaus cannot be resolved. 

The second is more complicated.
 ```bash
t/2_pl_compile.t ...... 
ok 1 - Compilation check: /opt/gridware/apps/cancerit/src/PCAP-core-1.6.1/t/../bin/diff_bams.pl
ok 2 - Compilation check: /opt/gridware/apps/cancerit/src/PCAP-core-1.6.1/t/../bin/bamToBw.pl
ok 3 - Compilation check: /opt/gridware/apps/cancerit/src/PCAP-core-1.6.1/t/../bin/bwa_aln.pl
not ok 4 - Compilation check: /opt/gridware/apps/cancerit/src/PCAP-core-1.6.1/t/../bin/xml_to_bas.pl

#   Failed test 'Compilation check: /opt/gridware/apps/cancerit/src/PCAP-core-1.6.1/t/../bin/xml_to_bas.pl'
#   at t/2_pl_compile.t line 40.
ok 5 - Compilation check: /opt/gridware/apps/cancerit/src/PCAP-core-1.6.1/t/../bin/bwa_mem.pl
not ok 6 - Compilation check: /opt/gridware/apps/cancerit/src/PCAP-core-1.6.1/t/../bin/gnos_pull.pl

#   Failed test 'Compilation check: /opt/gridware/apps/cancerit/src/PCAP-core-1.6.1/t/../bin/gnos_pull.pl'
#   at t/2_pl_compile.t line 40.
ok 7 - Compilation check: /opt/gridware/apps/cancerit/src/PCAP-core-1.6.1/t/../bin/bam_to_sra_sub.pl
ok 8 - Compilation check: /opt/gridware/apps/cancerit/src/PCAP-core-1.6.1/t/../bin/monitor.pl
ok 9 - Compilation check: /opt/gridware/apps/cancerit/src/PCAP-core-1.6.1/t/../bin/bam_stats.pl
1..9
# Looks like you failed 2 tests of 9.
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/9 subtests 
```
If I understand correctly what these tests do is simply to run "perl -c <perl_script>"
The two files with errors cannot run because they cannot get PCAP.pm. Adding 
```perl
BEGIN {
  use Cwd qw(abs_path);
  use File::Basename;
  unshift (@INC,dirname(abs_path($0)).'/../lib');
};
```
which other files have fixes this problem but "xml_to_bas.pl" still has a compilation problem:
Type of arg 1 to keys must be hash (not hash element) at (around line 85)
```
  my @columns = sort keys $first_record->{'metrics'};
```
Can you please advise if this is important or can be ignored?

**Comment by keiranmraine** [comment]
Can you confirm your perl version please, also have you an older version of PCAP-core installed already?

**Comment by ink1** [comment]
I'm on Scientific Linux 6.4: Perl version 5.10.1. Because I'm testing manually I set PERL5LIB to
/apps/cancerit/2015-03-19/lib/perl5:/apps/cancerit/2015-03-19/lib/perl5/x86_64-linux-thread-multi
but PCAP.pm is not there because the setup script has not done "make install" yet - it aborts on "make test".

**Comment by keiranmraine** [comment]
Hi, would you mind testing the hotfix branch on your setup please?

    git clone https://github.com/ICGC-TCGA-PanCancer/PCAP-core.git
    git checkout hotfix/v1.6.3
    ./setup INSTALL_LOC

**Comment by ink1** [comment]
The setup script run through to completion this time. No hiccups. Many thanks.
Moving on to BRASS.
