### ISSUE TITLE
How do I check if PCAP-core is installed?

### ISSUE THREAD

**Issue by komalsrathi** [ICGC-TCGA-PanCancer/PCAP-core#87]
Hi,

I used the following commands to install PCAP-core:

$ git clone https://github.com/ICGC-TCGA-PanCancer/PCAP-core
$ ./setup.sh /path/to/PCAP-core/1.10.0

I then added the bin to the PATH variable:
export PATH=/path/to/PCAP-core/1.10.0/bin:$PATH

and added the following to the PERL5LIB variable:
export PERL5LIB=/path/to/PCAP-core/1.10.0/lib/perl5:$PERL5LIB
export PERL5LIB=/path/to/PCAP-core/1.10.0/lib/perl5/x86_64-linux-thread-multi:$PERL5LIB 

Now, when I am trying to install cgpBattenberg, it is giving me an error:
$ ./setup.sh /path/to/cgpBattenberg/1.4.0
PREREQUISITE: Please install PCAP-core before proceeding:
  https://github.com/ICGC-TCGA-PanCancer/PCAP-core/releases

I checked the setup.sh file and ran line 80 in my terminal:
perl -le 'eval "require $ARGV[0]" and print $ARGV[0]->VERSION' PCAP
it returns the correct version number i.e. 1.10.0

But at line 54, it is unsetting the PERL5LIB and when I try to replicate the problem by unsetting PERL5LIB and re-run the above command, it doesn't return anything.

**Comment by keiranmraine** [comment]
Hi,

Firstly you don’t need to move the cloned repository the setup.sh script installs the the specified location and then the original clone/download is irrelevant.  You should also note that it using tagged releases is better practice:

https://github.com/ICGC-TCGA-PanCancer/PCAP-core/releases <https://github.com/ICGC-TCGA-PanCancer/PCAP-core/releases>

cgpBattenberg is expecting to find the PCAP install in the location that is specified for the setup.sh script.

The reasons for this are:

1. Each install clears the PERL5LIB to ensure that a clean environment is used, only including the destination and default libraries.
2. The PERL5LIB variable can become too long if you add each module set separately (gradually becoming a legacy issue).
3. You will additionally end up with t avery long $PATH variable (as that requires pre-pending with the corresponding bin folder)

As I’m finding many people wanting to install each tool to a separate versioned location I plan to add an environment variable for paths to include during the setup.sh execution.

Kind regards,

Keiran Raine
Principal Bioinformatician
Cancer Genome Project
Wellcome Trust Sanger Institute
